name: test, build and lint the project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Testing Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install modules with yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod
      - name: Typescript linting
        if: always()
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:ts
      - name: SCSS linting
        if: always()
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:scss

      - name: Run unit tests
        if: always()
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit
      - name: Build storybook bundle
        if: always()
        uses: borales/actions-yarn@v4
        with:
          cmd: storybook:build
      - name: Run screenshots loki tests
        if: always()
        uses: borales/actions-yarn@v4
        with:
          cmd: test:ui:ci